--Student functionality related data

--Student table
CREATE TABLE STUDENT (
    ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    NAME VARCHAR(30) NOT NULL,
    SURNAME VARCHAR(30) NOT NULL,
    PERSONALNUMBER BIGINT NOT NULL
 );

--Student data
INSERT INTO STUDENT (ID, NAME, SURNAME, PERSONALNUMBER) VALUES (1, 'Jonas', 'Zaltys', 38212219889);
INSERT INTO STUDENT (ID, NAME, SURNAME, PERSONALNUMBER) VALUES (2, 'Petras', 'Kalubauskas', 39812210123);
INSERT INTO STUDENT (ID, NAME, SURNAME, PERSONALNUMBER) VALUES (3, 'Jurgita', 'Butkute', 49512220811);

ALTER TABLE STUDENT ALTER COLUMN ID RESTART WITH 4;